language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku:git
  username: xinyuan.chen19@imperial.ac.uk
  password:
    secure: FZv/mL+2wyxlxZ4W1b/M7I7rcEjtz6MviXkTovTGvHwQD9ZG8VpxbFAm4Yeyc4BghYrG6MnpR2ruqenRdIdGsWJPbF6oT3s8R45bkXdd0JgObOJoYj/wEsMcTV8qAq+JLwtL09RfVaLVpdeufLRCq/B4NKOZWAf0m1CJTfGi0EbARLTsa2GnH9AAk4XTzE9aVmuSG50T+ifhWWyEdkj1RGj0lS+76TO5S28DHDrj8Hfr9Jl4PPZadGSr/6+nER6QyouKScDsZy2/JiqDCUeAXlvsWPxZMa+ceBWB1lWTgZLNUPSrRE+wcobIhWQyp7Uf1IXPrs0SljQe3GcZ8L1e7wgFAg+beEXvjunhxxOrtrUjgvj3UwILT+cIluuPfu/x718RNv7FbyXlB9FrUKjVPHj4lUj/Zr8j7Xba8l9hb0+27G05trgAUFoWq3ENLSpoO5qMlyXlPmCYgEpI7+s4pw1xVpt91B0fGbIVM01IN0/NOu8EIJEnDzhDnIooo302SChJLC6qVvr1NIXM5EjGeINTGh47vxyqChiVjpaw9wHD6TsTl1cIRpyNfMEYixXgoNVYjZyggd66ny5ecj8chIApqmrz3kyEYRb6BkFJlp2zV7fAfIvCJoptnXzkclVE762DSHqBb+aV37S8KfulzffMlmwBWHE6Pr47OJTZ/cM=
  app: web-basics-test